### ISSUE TITLE
Validation fails for Cornell Birdcall data (Possibly due to differing sox versions?)

### ISSUE THREAD

**Issue by khughitt** [earthspecies/beans#1] opened 2023-05-19 02:09 UTC
Greetings!

I'm currently attempting to download & validate the benchmark datasets using `download_data.sh`.

The validation fails, however, upon encountering an unexpected md5 hash for one of the converted Kaggle birdcall mp3s:

```
Validating data/cbi/wav/XC135460.wav ...
Validating data/cbi/wav/XC140298.wav ...
Traceback (most recent call last):
  File "scripts/validate_data.py", line 8, in <module>
    check_md5(path, md5)
  File "/mnt/ssd2/software/beans/beans/utils.py", line 29, in check_md5
    assert False, f'md5 for {file_name} does not match'
AssertionError: md5 for data/cbi/wav/XC140298.wav does not match
```

**Expected**:

```
data/cbi/wav/XC140298.wav	ed0b40766bd7cd4749fa4245fb964e08
```

**Actual**:

```
604ac649f277e4fdf8024aa88a860ec3  cbi/wav/XC140298.wav
```

I tried re-running the `sox` command manually, and the result is the same.

I'm wondering if it could be an issue relating to the version of sox used to generate the hashes, vs what I have installed?

If that is the case, perhaps the pipeline could be updated to use sox from [conda-forge](https://anaconda.org/conda-forge/sox), rather than the host OS's version?
I would imagine they are providing a version that includes mp3 support.

I did not notice any errors during the kaggle download/extraction steps but, just in case:

```
❯ md5sum cbi/train_audio/aldfly/XC140298.mp3

a8e49cde1b1bb086845716cbdca14c60  cbi/train_audio/aldfly/XC140298.mp3

❯ l cbi/train_audio/aldfly/XC140298.mp3
494 KB Thu Jun 18 22:02:34 2020  cbi/train_audio/aldfly/XC140298.mp3
```

**System info**:

- Arch Linux
- sox v14.4.2

Thanks for taking the time to put together this great resource, and for sharing it with the community!

Cheers,
Keith

**Comment by mhagiwara** [comment] 2024-10-13 15:41
Hello @khughitt I'm sorry for the delays following up on this. I used SoX v14.4.2 on Ubuntu 20.04.6 LTS. It seems like there are other people having the same issue. I'll follow up and think of ways to make this more reproducible (e.g., by hosting the preprocessed data). I'll keep you posted.

**Comment by chengyutang** [comment] 2024-10-16 23:03
Hello @mhagiwara Thank you for addressing dependencies and data hosting in the recent update. I had the same issue, and after downgrading `torch` and `torchaudio` from the latest version to `torch==1.12.1` and `torchaudio==0.12.1`, all files can now be successfully verified for me. So the problem is likely caused by different chunking results using different PyTorch versions.

**Comment by mhagiwara** [comment] 2024-10-16 23:23
@chengyutang Great, thank you for verifying this. Closing this for now.

**Closed as completed by mhagiwara** 2024-10-16 23:23 UTC
